# --- Defaults --- Adapted From ROMA Codebase

# --- pymarl options ---
meta_type: "normal"
runner: "episode" # Runs 1 env for an episode
mac: "shared" # Basic controller
env: "cleanup" # Environment name
env_args: {} # Arguments for the environment
learner: q_learner
batch_size_run: 1 # Number of environments to run in parallel
test_nepisode: 20 # Number of episodes to test for
test_interval: 2000 # Test after {} timesteps have passed
test_greedy: False # Use greedy evaluation (if False, will set epsilon floor to 0
log_interval: 2000 # Log summary of stats after every {} timesteps
runner_log_interval: 2000 # Log runner stats (not test stats) every {} timesteps
learner_log_interval: 2000 # Log training stats every {} timesteps
use_cuda: True # Use gpu by default unless it isn't available
buffer_cpu_only: True # If true we won't keep all of the replay buffer in vram

# --- Logging options ---
use_tensorboard: True # Log results to tensorboard
save_model: True # Save the models to disk
save_model_interval: 200000 # Save models after this many timesteps
checkpoint_path: "" # Load a checkpoint from this path
evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)
load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
save_replay: False # Saving the replay of the model loaded from checkpoint_path
local_results_path: "results" # Path for local results

# --- RL hyperparameters ---
gamma: 0.99
batch_size: 32 # Number of episodes to train on
buffer_size: 32 # Size of the replay buffer
lr: 0.001 # Learning rate for agents
critic_lr: 0.0005 # Learning rate for critics
optim_alpha: 0.001 # RMSProp alpha  earning_rate=0.001,
optim_beta1: 0.9
optim_beta2: 0.999
optim_eps: 0.0001 # Adam epsilon
grad_norm_clip: 10 # Reduce magnitude of gradients above this L2 norm

# --- Agent parameters ---
# agent: "dgn_agent" # "rnn_agent_image_vec" # Default rnn agent
hidden_dim: 64
obs_agent_id: True
obs_last_action: False

# --- Experiment running params ---
repeat_id: 1
label: "default_label"

device: "cuda:0"
device_num: 0
