epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

buffer_size: 5000
control_dim: 2
# update the target network every {} episodes
target_update_interval: 200

power_structure_freeze_steps: 5

# use the Q_Learner to train
agent_output_type: "q"

control_estimator_hidden_sizes: [32,]
rnn_hidden_dim: 32 # Size of hidden state for default rnn agent
obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: True # Include the agent's last action (one_hot) in the observation

name: "modified_nash_q"