meta_type: "pq"
p_actor: "pq_agent"
q_actor: "pq_agent"
pq_actor_hidden_sizes: 32
pq_output_type: "pi_logits"
learner: "pq_q_learner"
runner: "pq_episode"
mac: "shared_pq"
env_steps_every_pq: 40000
max_pq_training_steps: 10000
pq_sample_runs: 400

name: "pq_dgn_q_learning"